language: java
jdk:
  - openjdk8
os:
  - linux

cache:
  directories:
   - $HOME/.m2

jobs:
  include:
    - stage: "Build"
      name: "Build Package"
      script: "mvn clean compile"
    - stage: "Unit-Test"
      name: "Unit Test"
      script: mvn surefire:test